### ISSUE TITLE
Different order resolution between the doc and the lib behavior

### ISSUE THREAD

**Issue by clojure-paris** [yogthos/config#11]
The documentation and the lib code, hence its behavior, are different. The doc states that: 

> The configuration is resolved in the following order, the variables found in later configurations will replace those declared earlier:
> 
> 1. `config.edn` on the classpath
> 2. EDN file specified using the `config` environment variable
> 2.  `.lein-env` file in the project directory
> 3. Environment variables
> 4. Java system properties

The code reads first the `.lein-env`, then the values are overridden by the `config.edn` file and not the inverse as stated in the documentation. Personally, I would prefer the behavior defined in the documentation to allow a dev environment to override some `stuff` in config file and by env vars in prod environment. 
```
(defn load-env
  "Generate a map of environment variables."
  [& configs]
  (let [env-props (merge-maps (read-system-env) (read-system-props))]
    (apply
      merge-maps
      (read-env-file ".lein-env")
      (read-env-file (io/resource ".boot-env"))
      (read-config-file "config.edn")
      (read-env-file (:config env-props))
      env-props
      configs)))
```

Would you accept a PR to fix the code?

**Comment by jgrodziski** [comment]
Sorry, I opened the issue with a different account (the one to run the clojure Paris meeetup) instead of my personal one.

**Comment by yogthos** [comment]
No problem, and a PR would be very welcome. :)
