### ISSUE TITLE
Management of private configurations

### ISSUE THREAD

**Issue by diavoletto76** [yogthos/config#17]
Hi, would you consider the option to add `config-private.edn` to the list of config resources? The idea is allow to store _private configs_ in a separate file (not to be checked-in in CVS).

Thank you.

**Comment by yogthos** [comment]
I've updated the library to make the helper functions public, so it's possible to load additional config files via `load-env` function, e.g:

```clojure
(ns config-test.core
  (:require
   [config.core :as config]))

(def env
  (-> (System/getenv "private_config")
      (config/read-config-file)
      (config/load-env)
      (delay)))

(defn -main []
  (println 
   "public:"  (:public @env)
   "\nprivate:" (:private @env)))
```

This will load the default configuration, then merge the one found in the file identified by the `private_config` env variable on top of it.

**Comment by diavoletto76** [comment]
Thank you.
