### ISSUE TITLE
Namespaces of keywords are stripped out of configs not bundled into jar

### ISSUE THREAD

**Issue by rsslldnphy** [yogthos/config#18]
We have a config file that looks something like this:

```
{:pulsar/url "abc"
 :postgres/url "xyz"}
```
...which works fine with a `config.edn` bundled into the jar. However when we do `java -Dconfig=foo.edn -jar app.jar` the namespaces are stripped out with a warning:

```
Warning: config key :pulsar/url has been corrected to :url
Warning: config key :postgres/url has been corrected to :url
```

This is caused by the `sanitize-keys` function which is called in `read-env-file` but not `read-config-file`: https://github.com/yogthos/config/blob/051e229d4f816affaa8310db5d4f709f428502b0/src/config/core.clj#L36-L39

I'm happy to submit a pull request to make `sanitize-keys` support namespaced keywords but I wanted to check first what the intention of the sanitization was to make sure I took an approach consistent with the original aims of the function. Thanks!

**Comment by yogthos** [comment]
Hi,

Making the behavior inconsistent was an omission on my part, and a PR for a fix would be much appreciated. :)

**Comment by rsslldnphy** [comment]
Thanks - will make a PR!

Just to be clear though, do you mean:

1. `sanitize-keys` shoud _also_ be run for `config.edn` on the classpath, and should support namespaced keywords.
2. `sanitize-keys` shoud _also_ be run for `config.edn` on the classpath, and should NOT support namespaced keywords.
3. `sanitize-keys` should only be run for environment variables and system properties, not for `edn` files, whether they are on the classpath or specified on the command line.

I noticed that `sanitize-keys` also lower-cases keys and replaces underscores with hyphens - so options 1 and 2 would break the config of anyone who uses `config.edn` on the classpath with uppercase or snake case keys. So I will assume that you mean option 3 for now and make a PR accordingly, but just thought I'd double check and explain my reasoning!

**Comment by yogthos** [comment]
I think if the config is specified in EDN, then it should be safe to assume that the keys are in a canonical format. The parsing only needs to be done for environment variables and JVM arguments.
