### ISSUE TITLE
loading external configuration

### ISSUE THREAD

**Issue by zweifisch** [yogthos/config#2]
I used to loading configuration from external file in production environment, like `/etc/myapp/config`. The benefit is that the config file does not need to be put in VCS, and can be managed by tools like ansible and puppet. But with edn-config, the config file must be bundled in the jar. Is that best practice in clojure/java world?

**Comment by yogthos** [comment]
The config can still be read from the environment. The library augments the [environ](https://github.com/weavejester/environ) library that reads config from system properties and Java properties with the ability to additionally read the config from local properties. If you're using environment variables then you should just use environ directly.
