### ISSUE TITLE
Why can't I read the edu file.

### ISSUE THREAD

**Issue by leon-zhang-guoao** [yogthos/config#21]
```
  :profiles {:uberjar {:aot [vend-license-service.core]}
             :dev {:resource-paths ["config/dev"]}}
```
This is my project.clj file.
├─config
│  └─dev
My edn file is placed in dev. config.edn

This is my packaging order.

lein with-profile dev uberjar

This is the command I run.
java -Dconfig="config.edn" -jar xxx-standalone.jar

The program runs, but the edn file cannot be read.

**Comment by leon-zhang-guoao** [comment]
lein run program works perfectly. 
The jar operation is unsuccessful and the edn file cannot be read.

**Comment by yogthos** [comment]
when you use `-Dconfig` then the file path is relative to the folder you're running `java` command from. So, if the file is in `config/dev/config.edn` and you're running from the root folder of the app, you'd have to do `java -Dconfig="config/dev/config.edn" -jar xxx-standalone.jar`.

**Comment by leon-zhang-guoao** [comment]
> 
> 
> when you use `-Dconfig` then the file path is relative to the folder you're running `java` command from. So, if the file is in `config/dev/config.edn` and you're running from the root folder of the app, you'd have to do `java -Dconfig="config/dev/config.edn" -jar xxx-standalone.jar`.
I tried it and it still doesn't work.

**Comment by yogthos** [comment]
can you run `tree -d` command in the root folder?

**Comment by leon-zhang-guoao** [comment]
├─config
│  └─dev
├─doc
├─resources
│  └─log
├─src
│  └─vend_license_service
│      ├─common
│      ├─models
│      └─service
└─test
    ├─es_query
    └─example

**Comment by leon-zhang-guoao** [comment]
![捕获](https://user-images.githubusercontent.com/52643518/114799751-f4be5100-9dca-11eb-93ce-b1d02e542519.PNG)

**Comment by yogthos** [comment]
so yeah if you're running from this folder, the path should be `config/dev/config.edn`. There's nothing fancy with the config resolution as you can see [here](https://github.com/yogthos/config/blob/master/src/config/core.clj#L54). It just tries to read it from the given path.

**Comment by leon-zhang-guoao** [comment]
Thank you, I did it under /target, so I didn't read it. It's solved now.
