### ISSUE TITLE
give file path in :ressource-paths

### ISSUE THREAD

**Issue by nha** [yogthos/config#3]
I end up with the following structure : 

config
├── dev
│   └── config.clj
├── prod
│   └── config.clj
...

There is only one file per folder. Why not specify a file path instead of a directory path ? What is the rationale behind it ?

Thanks

**Comment by yogthos** [comment]
It's just what I needed at the time, using the folder would make sense as well. The only trick would be in how you merge the config from different resources. If you'd like to update the library to work that way I'll take a pull request.

**Comment by nha** [comment]
@yogthos Thank you for the reply. I'll try to find a bit of time to have a look at this. Would you be against the inclusion of a library to check if the path is a directory or not (https://github.com/Raynes/fs) ?

**Comment by yogthos** [comment]
yeah that should be fine, also you can take a look [here](https://github.com/cryogen-project/cryogen-core/blob/85ea98f0ffa552eee3d9fb6f48bfb105bf0944dd/src/cryogen_core/io.clj#L25) for an example of doing a similar task.
