### ISSUE TITLE
lein 2.6.1 breaks parsing .lein-env with aot compile

### ISSUE THREAD

**Issue by alan-saar** [yogthos/config#4]
when uberwar with lein 2.6.1 i received:
`WARNING: failed to parse .lein-env No dispatch macro for: =`
I think is related to this
https://github.com/technomancy/leiningen/issues/2096

**Comment by yogthos** [comment]
I think the issue would be with the lein plugin rather the config library. If you're using `leing-environ`, try updating to `1.0.2`. As a side note, Luminus now defaults to using [cprop](https://github.com/tolitius/cprop), and [lein-cprop](https://github.com/luminus-framework/lein-cprop).

**Comment by alan-saar** [comment]
You are right. Thank You.
The issue is with the lein-environ.
I'm using luminus template 2.9.10.5. 
Changing in project.clj  to [lein-environ "1.0.2"] didn't solve the issue.
Changing in project.clj to [lein-cprop "1.0.1"] did solve the issue.
Luminus is moving fast!

**Comment by yogthos** [comment]
it has some growth spurts now and then ;)
