### ISSUE TITLE
Reloading question

### ISSUE THREAD

**Issue by crinklywrappr** [yogthos/config#6]
When working with config at the repl is there a recommended way to reload the env map?

**Comment by yogthos** [comment]
The library uses `defonce` to initialize the config, so there really isn't a good way to do reloading. I'm actually using [cprop](https://github.com/tolitius/cprop) myself nowadays, and it allows reloading the config at runtime.

**Comment by crinklywrappr** [comment]
That's what it looked like.  Thanks.
